MS_GRAPH_USERNAME: "usernamehere@xxxxx.onmicrosoft.com"
MS_GRAPH_PASSWORD: "xxxxxxxxxxxx"
MS_GRAPH_CLIENT_ID: "xxxxx-xxxx-xxx-xxxxxx-xxxxxxx"
MS_GRAPH_CLIENT_SECRET: "xxxXXXxxXXXxxxXXXxxXXXXXXXXxxxxxx="
MS_GRAPH_TENANT: "xxxxx.onmicrosoft.com"